sudo: required
services: 
  - docker
# language: node_js
# node_js:
#   - "stable"

# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
# using the Dockerfile.dev to test run test cases 
before install: 
  - docker build -t ganesh/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run ganesh/react-test npm run test -- --coverage

# building the docker container images using dockerfile in the relative folders for production build.
after_success:
  - docker build -t ganesh/multi-client ./client
  - docker build -t ganesh/multi-nginx ./nginx
  - docker build -t ganesh/multi-server ./server
  - docker build -t ganesh/multi-worker ./worker


  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin


  # Take the above images & push  to docker hub.

  - docker push ganesh/multi-client
  - docker push ganesh/multi-nginx
  - docker push ganesh/multi-server
  - docker push ganesh/multi-worker









  